# exec-once = $terminal

exec-once = ~/.config/hypr/bin/waybar.sh
exec-once = hyprpaper
exec-once = /usr/lib/xfce-polkit/xfce-polkit

exec-once = nm-applet --indicator

exec-once = swaymsg layout default
exec-once = swaync
exec-once = swayosd-server

exec-once = wl-clip-persist --clipboard regular --reconnect-tries 0
exec-once = wl-paste --type text --watch cliphist store

exec-onec = blueman-applet

exec-once = 1password --silent
exec-once = tailscale systray

exec-once = ~/.config/screenlayout/work.sh
