[preferred]
default=wlr
org.freedesktop.impl.portal.ScreenCast=wlr
org.freedesktop.impl.portal.Screenshot=wlr
org.freedesktop.impl.portal.Inhibit=none
# DBusName=org.freedesktop.impl.portal.desktop.wlr
# Interfaces=org.freedesktop.impl.portal.Screenshot;org.freedesktop.impl.portal.ScreenCast;
# UseIn=wlroots;mango;sway;Wayfire;river;phosh;Hyprland;
